config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :charges
  get 'event/stripe_callback'
  get 'event/payment_profile'

  get "/stripe_connect/callback", to:"barbers#stripe_callback"

  resources :password_resets,     only: [:new, :create, :edit, :update]
  get 'sessions/new'
  resources :customers
  resources :barbers
  resources :appointments
  root :to => 'barbers#index'
  get '/search' => 'barbers#search'
  get '/barber/appointment' => 'barbers#appointment'

  get '/customers/new' => 'customers#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  get '/day_schedule/new', to: 'day_schedule#new'
  post '/day_schedules', to: 'day_schedule#create'
  get '/day_schedule/update', to: 'day_schedule#update'
  post '/day_schedule/update', to: 'day_schedule#set_available'

  get '/day_schedules', to: 'day_schedule#show'
  post '/services', to: 'services#create'
  post '/services/get_service', to: 'services#get_service'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/barber.rb
class Barber < ApplicationRecord
  attr_accessor :reset_token, :remember_token, :activation_token
  include ValidateEmailUniquenessAcrossModels
  has_many :day_schedules
  has_many :services 
  has_many :customers, through: :services
  validates :name,  presence: true
  validates :email, presence: true, uniqueness: true
  has_secure_password
  before_create :create_activation_digest
  def get_appointment
    @appointment = Appointment.new(@barber)
  end
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end
  def send_activation_email
   BarberMailer.account_activation(self).deliver_now
 end
  def remember
    self.remember_token = Barber.new_token
    update_attribute(:remember_digest, Barber.digest(remember_token))
  end
  def authenticated?(attribute, token)
   digest = send("#{attribute}_digest")
   return false if digest.nil?
   BCrypt::Password.new(digest).is_password?(token)
  end
  def forget
    update_attribute(:remember_digest, nil)
  end
  def Barber.new_token
    SecureRandom.urlsafe_base64
  end
  def Barber.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  def create_reset_digest
    self.reset_token = Barber.new_token
    update_attribute(:reset_digest,  Barber.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end
  def send_password_reset_email
    BarberMailer.password_reset(self).deliver_now
  end
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  private

  def create_activation_digest
      self.activation_token  = Barber.new_token
      self.activation_digest = Barber.digest(activation_token)
    end
end

app/controllers/barbers_controller.rb
class BarbersController < ApplicationController
require 'http'
require 'nokogiri'
require "json"
require "httparty"


  before_action :set_barber, only: [:show, :edit, :update, :destroy]

  # GET /barbers
  # GET /barbers.json

  def search
    @barbers = if params[:name]
    Barber.where('name LIKE ?', "%#{params[:name]}%")
  else
    @barbers = nil
  end
  end

  def index
    # gon.test = "test"
    @barbers = Barber.all

  end

  def stripe_callback
            options = {
              site: 'https://connect.stripe.com',
              authorize_url: '/oauth/authorize',
              token_url: '/oauth/token'
            }
            code = params[:code]
            client = OAuth2::Client.new(ENV['STRIPE_CONNECT_CLIENT_ID'], ENV['SECRET_KEY'], options)
            @resp = client.auth_code.get_token(code, :params => {:scope => 'read_write'})
            @access_token = @resp.token
            @barber.update!(uid: @resp.params["stripe_user_id"]) if @resp
            flash[:notice] = "Your account has been successfully created and is ready to process payments!"
  end

   # //this is where a user will be able to see their balance info
  def payment_profile
      @account = Stripe::Account.retrieve("#{@barber.uid.to_s}") if @barber.uid.present?
      @balance = Stripe::Balance.retrieve() if @barber.uid.present?
  end

  # GET /barbers/1
  # GET /barbers/1.json
  def show
    @date = gon.day

    if @barber.url == "" or @barber.url.nil?
      p "BARBER.URL IS EMPTY"
      gon.barberlatitude = 25.761681

      gon.barberlongitude = -80.191788
    else
      p "BARBER.URL IS PRESENT"

      example = (@barber.url).split("biz/")

      business_id = example.last
      url = "#{API_HOST}#{BUSINESS_PATH}#{business_id}"

      response = HTTP.auth("Bearer #{API_KEY}").get(url)

      #lookup has the complete response:
      lookup = response.parse

      @barber.barberName= lookup["name"]
      #
      @barber.phone = lookup["display_phone"]
      #
      @barber.address= lookup["location"]["display_address"]
      @barberstreet = lookup["location"]["display_address"][0]
      @barbercitystatezip = lookup["location"]["display_address"][1]
      #
      @barber.rating = lookup["rating"]
      #
      @barber.photoUrl = lookup["photos"]
      @barberphotos = lookup["photos"]
      gon.barberlatitude = lookup["coordinates"]["latitude"]
      gon.barberlongitude = lookup["coordinates"]["longitude"]
    end


  end


  # GET /barbers/new
  def new
    @barber = Barber.new

  end

  # GET /barbers/1/edit
  def edit


    @service = Service.new
    times = [30, 60, 90, 120, 150, 180]
    @duration = times.map do |time|
      "#{time} minutes"
    end
    @barber_id = params[:id]


  end

  # POST /barbers
  # POST /barbers.json
  def create
    @barber = Barber.new(barber_params)
    @barber.url = params[:barber][:url]    #save in the table the params introduced
    @barber.barberName = params[:barber][:barberName]
    @barber.phone = params[:barber][:phone]
    @barber.address = params[:barber][:address]
    @barber.photoUrl = params[:barber][:photoUrl]





    if @barber.url == "" or @barber.url.nil?
      p "BARBER.URL IS EMPTY"
      gon.barberlatitude = 25.761681
      gon.barberlongitude = -80.191788
    else
      example = (@barber.url).split("biz/")

      business_id = example.last
      url = "#{API_HOST}#{BUSINESS_PATH}#{business_id}"

      response = HTTP.auth("Bearer #{API_KEY}").get(url)

      #lookup has the complete response:
      lookup = response.parse

      @barber.barberName= lookup["name"]
      #
      @barber.phone = lookup["display_phone"]
      #
      @barber.address= "#{lookup["location"]["display_address"][0]}, #{lookup["location"]["display_address"][1]}"

      @barber.rating = lookup["rating"]

      @barber.photoUrl = lookup["photos"][0]
    end



      if @barber.save
        # gon.clicked = false
        @barber.send_activation_email
        logout(@barber)
        redirect_to root_url
        flash[:info] = "Please check your email to activate your account."
      else
        render :new
      end
  end

  # PATCH/PUT /barbers/1
  # PATCH/PUT /barbers/1.json
  def update
    respond_to do |format|
      if @barber.update(barber_params)
        format.html { redirect_to @barber, notice: 'Barber was successfully updated.' }
        format.json { render :show, status: :ok, location: @barber }
      else
        format.html { render :edit }
        format.json { render json: @barber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barbers/1
  # DELETE /barbers/1.json
  def destroy
    @barber.destroy
    respond_to do |format|
      format.html { redirect_to barbers_url, notice: 'Barber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def analytics
  end

  private
    def logout(user)
      session.delete(:user_id)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_barber
      @barber = Barber.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barber_params
      params.require(:barber).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/barbers_helper.rb
module BarbersHelper
end

app/views/barbers/_calendar.html.erb
  <%= month_calendar do |date|%>
    <%if DaySchedule.find_by(barber_id: @barber.id, date_id: date) %>
      <%= link_to day_schedules_path(date: date, barber_id: @barber.id), remote: true, class:"calendar-cell" do %>
      <div class="individual_day" data-day="<%= date %>" style="background-color: #ABFCBE; position:relative; height:100%; width:100%;">
        <%= date.day%>
      </div>
      <%end%>
    <%else %>
      <div class="individual_day" data-day="<%= date %>" style=" position:relative; height:100%; width:100%;">
        <%= date.day%>
        <span>
          <span>
      </div>
    <%end %>
  <%end%>

app/views/barbers/_create_calendar.html.erb
<%= month_calendar do |date|%>
  <%if  DaySchedule.find_by(barber_id: @barber.id, date_id: date)%>
    <%= link_to day_schedule_update_path(date: date, barber_id: @barber.id), remote: true, class:"calendar-cell" do %>
    <div class="individual_day" data-day="<%= date %>" style="background-color: #ABFCBE; position:relative; height:100%; width:100%;">
      <%= date.day%>
    </div>
    <%end%>
  <%else%>
    <%= link_to day_schedule_new_path(date: date, barber_id: @barber.id), remote: true, class:"calendar-cell" do %>
    <div class="individual_day" data-day="<%= date %>" style="position:relative; height:100%; width:100%;">
      <%= date.day%>
    </div>
    <%end%>
  <%end%>
<%end%>

app/views/barbers/_form.html.erb
<% if flash[:notice] %>
    <div id="notice" style="color: red;"><%= flash[:notice] %></div>
<% end %>

<%= form_with(model: barber, local: true) do |form| %>
  <% if @barber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(barber.errors.count, "error") %> prohibited this barber from being saved:</h2>

      <ul>
      <% barber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field" style="text-align:center;">
    <%= form.label :name %>
    <%= form.text_field :name, id: :barber_name, placeholder: "Name", class: "form-control" %>
  </div>

  <div class="field" style="text-align:center;">
    <%= form.label :email %>
    <%= form.text_field :email, id: :barber_email, placeholder: "Email", class: "form-control" %>
  </div>
  <div class="field" style="text-align:center;">
    <%= form.label :password %>
    <%= form.text_field :password, id: :barber_password, placeholder: "Password", class: "form-control"  %>
  </div>
  <div class="field" style="text-align:center;">
    <%= form.label :password_confirmation %>
    <%= form.text_field :password_confirmation, id: :barber_password_confirmation, placeholder: "Password Confirmation", class: "form-control"  %>
  </div>
  <div class="field" style="text-align:center;">
    <%= form.label :Yelp_url %>
    <%= form.text_field :url, id: :barber_url, placeholder: "Url", class: "form-control"  %>
  </div>
  <br>

  <div class="field" style="text-align:center;">
    <%= form.label :Barber_Name %>
    <%= form.text_field :barberName, id: :barber_barberName, placeholder: "Barber Name", class: "form-control"  %>
  </div>
  <br>

  <div class="field" style="text-align:center;">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :barber_phone, placeholder: "Phone", class: "form-control"  %>
  </div>
  <br>

  <div class="field" style="text-align:center;">
    <%= form.label :address %>
    <%= form.text_field :address, id: :barber_address, placeholder: "Address", class: "form-control"  %>
  </div>
  <br>

  <div class="field" style="text-align:center;">
    <%= form.label :Photo_Url %>
    <%= form.text_field :photoUrl, id: :barber_photoUrl, placeholder: "Photo Url", class: "form-control"  %>
  </div>
  <br>

  <div class="actions">
    <p style="text-align:center;">
    <%= form.submit  class: "btn btn-primary btn-lg" %>
    </p>
  </div>

<%end%>

<h2>Plan your schedule:</h2>
<%=render 'create_calendar'%>



<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 style="text-align:center;" class="modal-title">Plan your Schedule</h4>
      </div>
      <div id="schedule_model">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">

      </div>
    </div>
  </div>
</div>

app/views/barbers/edit.html.erb
<div class="container">
  <br>
  <h1 style="text-align:center;">Editing Barber</h1>
  <hr>
  <h2 style="text-align:center;">Create a Service<h2>

    <%= render 'services/form' %>
    <%if !Service.find_by(barber_id: params[:id]) == nil? %>
      <b>Current Services You Offer</b> <br>
      <%Barber.find(params[:id]).services.each do |service| %>
      <div class="individual_service" style="border: solid;">
        <span>
          <%= service.description %>
        </span>
        <span>
          $<%= service.price %>
        </span>
        <span>
          <%= service.time_slots * 30 %> minutes
        </span>
      </div>
      <%end %>
    <%end %>
  <%= render 'form', barber: @barber %>
</div>








<body class="viewBody">
 <div class="content" >
   <br>
  <%= link_to 'Show', @barber, class:"btn btn-success" %> |
  <%= link_to 'Back', barbers_path, class:"btn btn-primary" %>

 </div>
</body>

app/views/barbers/index.html.erb
        <!-- Masthead -->
      <header class="masthead text-white text-center" >
        <div class="overlay"></div>
        <div class="container">
          <div class="row">
            <div class="col-xl-9 mx-auto">
              <h1 class="mb-5">PayCut <br> <span style="font-size:24px;">A modern way to get a hair cut.</span></h1>
            </div>
            <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
              <%= form_tag '/search', method: "get" do %>
                <div class="form-row">
                  <div class="col-12 col-md-9 mb-2 mb-md-0">
                    <%= search_field_tag :name, nil, class: "form-control form-control-lg", placeholder: "Search Barbers"   %>
                  </div>
                  <div class="col-12 col-md-3">
                    <%= submit_tag("Search", class: "btn btn-block btn-lg btn-info") %>
                  </div>
                </div>
                <% end %>
            </div>
          </div>
        </div>
      </header>

    <main role="main">
      <div class="background" style="padding-top:50px; padding-bottom:50px;">
      </div>
      <div class="barber">
      <div class="row" style="padding-top:50px; padding-bottom:50px;">
        <div class="col-md-7 order-md-1">

        </div>


        <div class="col-md-4 order-md-2">
          <div class="bg-light" style="border-radius:10px;">
            <br>
            <h1 class=" text-center">Create a new Barber</h1>
            <ul style="font-size: 20px;margin-right:10px;">
              <li>
                Create an account and enjoy a close relationship with customers.<br>
              </li>
              <br>
              <li>
                Make schedules.
              </li>
              <br>
              <li>
                Show services.
              </li>
              <br>
              <li>
                Take advantage of an easy way to handle your barbershop
              </li>
              <br>
            </ul>
            <br>
            <center>
              <%= link_to 'New Barber', new_barber_path, class:"btn btn-info btn-lg" %>
            </center>
            <br>

          </div>


<!-- Masthead -->

        </div>
      </div>
    </div>

      <div class="background" style="padding-top:50px; padding-bottom:50px;">
      </div>



      <div class="container">
        <p id="notice"><%= notice %></p>

        <h1 style="text-align:center">PayCut</h1>


          <br>




             <div class="row justify-content-md-center">
              <% @barbers.each do |barber| %>

              <div class="box" style="margin:15px;">
                <div class="col-md-12" >
                  <div class="thumbnail">
                    <h2 style= "text-align: center; padding:10px 10px 0 10px;"><%= barber.name %></h2>
                    <% if barber.url == "" or barber.url.nil? %>

                      <% if barber.photoUrl == "" or barber.photoUrl.nil? %>
                          <%=link_to image_tag("Home1.jpg", size: "200x150", style: "border-radius:20px;"), barber, class: "img-circle"%>
                      <% else %>
                          <%=link_to image_tag(barber.photoUrl, size: "200x150", style: "border-radius:20px;"), barber, class: "img-circle"%>
                      <% end %>
                          <div class="caption" style= "text-align: center">
                            <p>
                              <%=barber.barberName%>
                            </p>
                            <p>
                              <% if barber.address == "" or barber.address.nil? %>
                              <% else %>
                              <%=barber.address%>
                              <% end %>
                            </p>
                            <p>
                              <% if barber.phone == "" or barber.phone.nil? %>
                              <% else %>
                              <%=barber.phone%>
                              <% end %>
                            </p>
                          </div>


                    <% else %>
                      <%=link_to image_tag(barber.photoUrl, size: "200x150", style: "border-radius:20px;"), barber, class: "img-circle"%>

                        <div class="caption" style= "text-align: center">
                          <p>
                            <%=barber.barberName%>
                          </p>
                          <p>
                            <%=barber.address%>
                          </p>
                          <p>
                            <%=barber.phone%>
                          </p>
                          <p>
                            <%=barber.rating%>
                            <% barber.rating.to_i.times do  %>
                             <span class="fa fa-star checked"></span>
                            <% end %>
                          </p>

                        </div>
                    <% end %>



                  </div>
                </div>
              </div>
              <% end %>
            </div>


          <br>



        <center>
            <% if current_user%>
            <%= link_to 'Logout', logout_path%>
            <%else%>
            <%= link_to 'Login', login_path, class:"btn btn-success btn-lg" %>
            <%end%> |


            <%= link_to 'Get Started', new_customer_path, class:"btn btn-primary btn-lg" %>

        </center>



      </div><!-- /.container -->

    </main>

app/views/barbers/new.html.erb
<div class="container">
  <br>
  <h1 style="text-align:center;">New Barber</h1>
  <hr>
  <%= render 'form', barber: @barber %>
</div>

<body class="viewBody">
 <div class="content" >
   <br>
   <%= link_to 'Back', barbers_path, class:"btn btn-primary btn-lg" %>
   <div id= "schedule_model"></div>
 </div>
</body>

app/views/barbers/search.html.erb
<header class="masthead1 text-white text-center" >
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <h1 class="mb-5">PayCut <br> <span style="font-size:24px;">A modern way to get a hair cut.</span></h1>
      </div>
      <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
        <%= form_tag('/search', method: "get") do %>
          <div class="form-row">
            <div class="col-12 col-md-9 mb-2 mb-md-0">
              <%= search_field_tag :name, nil, class: "form-control form-control-lg", placeholder: "Search Barbers"   %>
            </div>
            <div class="col-12 col-md-3">
              <%= submit_tag("Search", class: "btn btn-block btn-lg btn-info") %>
            </div>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</header>

   <br>

<div class="row justify-content-md-center">
    <%@barbers.each do |item|%>
    <div class="box" style="margin:15px;">
      <div class="col-md-12" >
        <div class="thumbnail">
          <h2 style= "text-align: center; padding:10px 10px 0 10px;"><%= item.name %></h2>
          <p style= "text-align: center">
            <%=link_to image_tag(item.photoUrl, size: "200x150", style: "border-radius:20px;"), item, class: "img-circle"%>
            <div class="caption" style= "text-align: center">
              <p>
                <%=item.barberName%>
              </p>
              <p>
                <%=item.address%>
              </p>
              <p>
                <%=item.phone%>
              </p>
              <p>
                <%=item.rating%>
                <% item.rating.to_i.times do  %>
                 <span class="fa fa-star checked"></span>
                <% end %>
              </p>
            </div>

          </div>
        </div>
      </div>
    <%end%>
</div>

<br>

app/views/barbers/show.html.erb
<div class="container-fluid">

<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">
    <!--Indicators-->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-1z" data-slide-to="1"></li>
        <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->
    <!--Slides-->
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <% if @barber.url == "" or @barber.url.nil? %>
          <%= image_tag "Home1.jpg", class: "mx-auto d-block", alt: "First slide"%>
          <%else %>
          <%= image_tag @barberphotos[0], class: "mx-auto d-block", alt: "First slide"%>
          <%end %>
        </div>
        <div class="carousel-item">
          <% if @barber.url == "" or @barber.url.nil? %>
          <%= image_tag "Home2.jpg", class: "mx-auto d-block", alt: "First slide"%>
          <%else %>
          <%= image_tag @barberphotos[1], class: "mx-auto d-block", alt: "Second slide"%>
          <% end %>
        </div>
        <div class="carousel-item">
          <% if @barber.url == "" or @barber.url.nil? %>
          <%= image_tag "Home3.jpg", class: "mx-auto d-block", alt: "First slide"%>
          <%else %>
          <%= image_tag @barberphotos[2], class: "mx-auto d-block", alt: "Third slide"%>
          <% end %>
        </div>
    </div>
    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->
</div>
<!--/.Carousel Wrapper-->

</div>





<body class="viewBody">
 <div class="content" >
   <br>

<p id="notice"><%= notice %></p>
<p style="font-size: 20px;">
  <strong>Barber:</strong>
  <%=@barber.name%>
</p>
<p style="font-size: 20px;">
  <strong>Email:</strong>
  <%= @barber.email %>
</p>

  <p style="font-size: 20px;">
    <strong>Barber shop:</strong>
    <%= @barber.barberName  %>
  </p>
  <p style="font-size: 20px;">
    <strong>Phone:</strong>
    <%= @barber.phone  %>
  </p>
  <p style="font-size: 20px;">
    <strong>Address:</strong>
    <%= @barberstreet  %>
    <%= @barbercitystatezip %>
  </p>

  <p style="font-size: 20px;">
    <strong>Rating:</strong>
    <%=@barber.rating%>
    <% @barber.rating.to_i.times do  %>
     <span class="fa fa-star checked"></span>
    <% end %>
  </p>


  <br>


<h2>Plan your schedule:</h2>
<div class="container">
  <%=render 'create_calendar'%>

</div>


<br>

<% if @barber.url == "" or @barber.url.nil? %>
<h2>Find our location:</h2>
<div class="container">
  <input id="pac-input" class="controls" type="text" placeholder="Type addres here">
  <div id="map" style="height:30em;"></div>

  <script src="https://maps.googleapis.com/maps/api/js?key=<%="#{ENV["MAPS"]}"%>&libraries=places&callback=initAutocomplete"
        async defer></script>

<% else %>
<!-- Googlemaps API -->
<h2>Our location:</h2>
<div class="container">
  <input id="pac-input" class="controls" type="text" placeholder="Search Box">
  <div id="map" style="height:30em;"></div>

  <script src="https://maps.googleapis.com/maps/api/js?key=<%="#{ENV["MAPS"]}"%>&libraries=places&callback=initAutocomplete"
        async defer></script>

</div>
<%end %>

<br>


<%= link_to 'Edit', edit_barber_path(@barber), class:"btn btn-success btn-lg" %> |
<%= link_to 'Destroy', @barber, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-info btn-lg"%> |

<%= link_to 'Back', barbers_path, class:"btn btn-primary btn-lg" %>





<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Plan your Schedule</h4>
      </div>
      <div id="schedule_model">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">

      </div>
    </div>
  </div>
</div>




</div>
</body>