config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :charges
  get 'event/stripe_callback'
  get 'event/payment_profile'

  get "/stripe_connect/callback", to:"barbers#stripe_callback"

  resources :password_resets,     only: [:new, :create, :edit, :update]
  get 'sessions/new'
  resources :customers
  resources :barbers
  resources :appointments
  root :to => 'barbers#index'
  get '/search' => 'barbers#search'
  get '/barber/appointment' => 'barbers#appointment'

  get '/customers/new' => 'customers#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  get '/day_schedule/new', to: 'day_schedule#new'
  post '/day_schedules', to: 'day_schedule#create'
  get '/day_schedule/update', to: 'day_schedule#update'
  post '/day_schedule/update', to: 'day_schedule#set_available'

  get '/day_schedules', to: 'day_schedule#show'
  post '/services', to: 'services#create'
  post '/services/get_service', to: 'services#get_service'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create


    @appointment = Appointment.new

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
      
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.fetch(:appointment, {})
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :customer%><br>
    <%= form.text_field :customer, id: :customer_name %>
  </div>
  <div class="field_2">
    <%= form.label :price%><br>
    <%= form.text_field :price, id: :appointment_price%>
  </div>



  <div class="actions">
    <%= form.submit %>

  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>
<div class="modal fade" tabindex="-1" role="dialog">
]
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Appointment</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path, remote: true %>

app/views/appointments/new.html.erb
<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/new.js.erb
$('.modal-body').html("<%= j render 'form', appointment: @appointment %>");
$('.modal').modal();

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> 
<%= link_to 'Back', appointments_path %>